services:
  - type: web
    name: jengamart
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:5000 app:app"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
